[package]
name = "ansible-sshman"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "3.2.20", features = ["derive"]}
serde = {version = "1.0.144", features = ["derive"]}
serde_yaml = "0.9.11"
tempfile = "3.3.0"