[package]
name = "ansible-sshman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.2.20", features = ["derive"]}
yaml-rust = "0.4.5"
serde = {version = "1.0.144", features = ["derive"]}
serde_yaml = "0.9.11"